installCRDs: true

serviceAccount:
  create: true
  name: external-secrets
  annotations:
    # IRSA role — Step M9 mein banaya tha
    eks.amazonaws.com/role-arn: arn:aws:iam::260699793439:role/gitops-demo-external-secrets

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    memory: 256Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

certController:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi