{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreRef }}
  labels:
    {{- include "demo-api.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "demo-api.fullname" . }}
  labels:
    {{- include "demo-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
    kind: SecretStore
  target:
    name: {{ include "demo-api.fullname" . }}-secret
    creationPolicy: Owner
  dataFrom:
    # Git mein sirf yeh PATH hai — actual value kabhi commit nahi hoti
    - extract:
        key: {{ .Values.externalSecret.remoteKey }}
{{- end }}